### ISSUE TITLE
Invalid Remote File URI

### ISSUE THREAD

**Issue by Spinsus** [dhoer/chef-chromedriver#4]
Chef::Exceptions::InvalidRemoteFileURI
  --------------------------------------
  "https://chromedriver.storage.googleapis.com/2.21\n/chromedriver_linux64.zip" is not a valid `source` parameter for remote_file. `source` must be an absolute URI or an array of URIs.

It looks like when trying to use knife solo to prepare my instance, on line 69 of the default recipe the new version variable is adding a line break to the end.

**Comment by dhoer** [comment]
That was fixed by #3. Upgrade to latest 1.2.1 release.

**Comment by Spinsus** [comment]
Thanks, much appreciated!
