### ISSUE TITLE
Installs 2.21 instead of latest 2.22 release

### ISSUE THREAD

**Issue by chris-orchard** [dhoer/chef-chromedriver#5]
I believe this is due to the file at http://chromedriver.storage.googleapis.com/LATEST_RELEASE not being updated to contain 2.22. I have logged an issue on Chromedriverr issues: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1396 to ask them to update the file.

Commenting here in case anyone else has this issue. Please feel free to close if no fix is required to the cookbook if the file is updated.

**Comment by dhoer** [comment]
It looks like 2.22 hasn't been officially released: https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by chris-orchard** [comment]
Ah hadn't checked there, just at http://chromedriver.storage.googleapis.com/index.html. The fact that a 2.22 folder with downloadable driver files in there made me assume it was released. Looks like you can get it manually even if it's not official yet.

**Comment by dhoer** [comment]
If you can't wait, you can set `node['chromedriver']['version']  = '2.2.2'` and it will install that version.

**Comment by chris-orchard** [comment]
I can wait as 2.21 driver works with latest stable Chrome 51 despite the release notes saying it only supports up to 50.

**Comment by dhoer** [comment]
This should now be using 2.22.  Let me know if it isn't.
